# Generated by Django 5.2.11 on 2026-02-20 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("clothing", "Clothing"),
                            ("wool", "Wool"),
                            ("fabric", "Fabric"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "Piece"),
                            ("yard", "Yard"),
                            ("meter", "Meter"),
                            ("kg", "Kg"),
                            ("bundle", "Bundle"),
                        ],
                        default="piece",
                        max_length=20,
                    ),
                ),
                ("price_cents", models.IntegerField()),
                ("currency", models.CharField(default="NGN", max_length=3)),
                ("stock_qty", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ("min_order_qty", models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ("qty_step", models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ("image_urls", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shops.shop",
                    ),
                ),
            ],
        ),
    ]
