# Generated by Django 5.2.11 on 2026-02-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock_qty",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
